name: Infrastructure Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up OpenStack CLI and YAML Linter
        run: |
          sudo apt update
          sudo apt install -y python3-openstackclient python3-heatclient yamllint

      - name: Lint Yaml file
        run: yamllint heat.yaml

      - name: Configure OpenStack Environment
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_PROJECT_DOMAIN_ID: ${{ secrets.OS_PROJECT_DOMAIN_ID }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
        run: echo "Configured OpenStack environment variables."

      - name: Deploy or Update OpenStack Stack
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_PROJECT_DOMAIN_ID: ${{ secrets.OS_PROJECT_DOMAIN_ID }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
        run: |
          if openstack stack show infrastructure-delivery-pipeline-stack >/dev/null 2>&1; then
            echo "Updating existing stack..."
            openstack stack update --existing --template heat.yaml infrastructure-delivery-pipeline-stack
          else
            echo "Creating new stack..."
            openstack stack create --template heat.yaml infrastructure-delivery-pipeline-stack
          fi

      - name: Deploy ToDo App
        env:
          FLOATING_IP: ${{ secrets.FLOATING_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          # Copy the todo_app folder to the server
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./todo_app ubuntu@$FLOATING_IP:/tmp/

          # Execute commands directly on the server
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$FLOATING_IP "
            sudo rm -f /var/www/html/index.html
            if [ -d ~/todo_app ]; then
              rm -rf ~/todo_app
            fi
            mv /tmp/todo_app ~/todo_app
            cd ~/todo_app
            export NVM_DIR=\"\$HOME/.nvm\"
            [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"
            nvm install 23.3.0
            nvm use 23.3.0
            npm install
            pm2 delete all || true
            pm2 start server.js
          "

